spring:
  application:
    name: ToDoApp
  datasource:
    embedded-database-connection: h2
    hikari:
      jdbc-url: jdbc:h2:mem:todo
  jpa:
    open-in-view: false
    generate-ddl: on
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: info
    org:
      springframework:
        security: trace
management:
  endpoints:
    web:
      exposure:
        include: '*'